set nocompatible

runtime! autoload/pathogen.vim
silent! call pathogen#helptags()
silent! call pathogen#runtime_append_all_bundles()

syntax on
set mouse=a

" Restore your cursor position in a file over several editing sessions.
set viminfo='10,\"100,:20,%,n~/.viminfo
au BufReadPost * if line("'\"") > 0|if line("'\"") <= line("$")|exe("norm '\"")|else|exe "norm $"|endif|endif
au BufEnter COMMIT_EDITMSG :normal 1G

set tabstop=4
set shiftwidth=4
set expandtab

retab
set autoindent
set smartindent
set cursorline
set splitbelow
set number
set noerrorbells
set visualbell
set t_Co=256
let g:indent_guides_auto_colors=0
let g:indent_guides_start_level=2
let g:indent_guides_guide_size=1

set background=dark
colorscheme solarized

" I love you and hate you AI.
set pastetoggle=<F6>
nnoremap <F6> :set invpaste paste?<CR>
set showmode

" NERD OUT
map <F5> :NERDTreeToggle<CR>

map kk <Esc>:w<CR>
